version: 2

jobs:
  install:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run: sudo docker-php-ext-install zip pdo
      - run: sudo composer self-update
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run: composer test
  build_mainapp:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml down -v
      - run: docker-compose -f docker-compose.yml build mainapp
      - run: docker-compose -f docker-compose.yml up -d mainapp
  build_db:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml down -v
      - run: docker-compose -f docker-compose.yml build db
      - run: docker-compose -f docker-compose.yml up -d db
  build_all:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml down -v
      - run: docker-compose -f docker-compose.yml build
      - run: docker-compose -f docker-compose.yml up -d mainapp db
  deploy:
    docker:
      - image: circleci/php:7.2-apache
    parallelism: 4
    working_directory: ~/ape
    steps:
      - checkout
      - attach_workspace:
          at: ~/ape
      - setup_remote_docker
      - run:
          name: Build and Deploy Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose down -v
            docker-compose build mainapp
            docker-compose push mainapp
workflows:
  version: 2
  all:
    jobs:
      - install
      - test:
          requires:
            - install
      - build_db:
          requires:
            - install
      - build_mainapp:
          requires:
            - install
      - build_all:
          requires:
            - build_db
            - build_mainapp
      - deploy:
          requires:
            - build_all
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - install
      - test
      - build_db
      - build_mainapp
      - build_all
      - deploy
